# Schema for the configuration files of the log module.

log.type.*:
  type: config_entity
  label: 'Log type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    name:
      type: label
      label: 'Type'

condition.plugin.log_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string
